# Generated by Django 4.2 on 2024-09-05 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='prova',
            options={'verbose_name_plural': 'proves'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='descriocio',
            new_name='descripcio',
        ),
        migrations.AddField(
            model_name='prova',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tester.categoria'),
        ),
        migrations.AlterField(
            model_name='intent',
            name='resultat',
            field=models.FloatField(default=0.0, help_text='Percentatge de compleció de la prova'),
        ),
    ]
