# Generated by Django 4.2 on 2024-09-06 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tester', '0002_alter_categoria_options_alter_prova_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('creacio', models.DateTimeField(auto_now=True)),
                ('actualitzacio', models.DateTimeField(auto_now=True)),
                ('descripcio', models.TextField(help_text="Descripció pública per a l'alumnat.")),
                ('anotacions', models.TextField(blank=True, help_text='Anotacions privades del docent.', null=True)),
                ('categoria', models.ManyToManyField(to='tester.categoria')),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='prova',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='intent',
            name='resultat',
            field=models.FloatField(default=0.0, help_text='Percentatge de compleció de les proves'),
        ),
        migrations.DeleteModel(
            name='Clau',
        ),
        migrations.AddField(
            model_name='prova',
            name='myset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.set'),
        ),
    ]
