# Generated by Django 4.2 on 2024-09-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0003_set_remove_prova_categoria_alter_intent_resultat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prova',
            old_name='myset',
            new_name='set',
        ),
        migrations.RemoveField(
            model_name='intent',
            name='prova',
        ),
        migrations.AddField(
            model_name='intent',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tester.set'),
        ),
    ]
