# Generated by Django 4.2 on 2024-09-11 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tester', '0004_rename_myset_prova_set_remove_intent_prova_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intent',
            name='alumne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intent',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tester.set'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='instruccio',
            field=models.TextField(help_text='"Comanda" a executar. Si s\'executa al servidor podeu emprar el codi "%IP" per referenciar la IP del client. No utilitzar cometes simples, o escapar-les amb \\ si son imprescindibles.'),
        ),
    ]
