# Generated by Django 4.2 on 2024-09-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0005_alter_intent_alumne_alter_intent_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='pes',
            field=models.FloatField(default=1.0),
        ),
    ]
