# Generated by Django 4.2 on 2024-09-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0006_prova_pes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='set',
            name='actiu',
            field=models.BooleanField(default=True),
        ),
    ]
