# Generated by Django 4.2 on 2024-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0007_prova_activa_set_actiu'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='tipus',
            field=models.CharField(choices=[('BASHCLI', 'Script bash al client'), ('BASHSRV', 'Script bash al servidor'), ('SELESRV', 'Script Selenium en JavaScript al servidor')], default='BASHCLI', max_length=8),
        ),
        migrations.AlterField(
            model_name='prova',
            name='connexio_ssh',
            field=models.BooleanField(default=True, help_text='DEPRECATED, no utilitzar.'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='instruccio',
            field=models.TextField(help_text='"Comanda" o instrucció a executar.'),
        ),
    ]
