# Generated by Django 4.2 on 2024-10-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0008_prova_tipus_alter_prova_connexio_ssh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prova',
            old_name='instruccio',
            new_name='script',
        ),
    ]
