# Generated by Django 4.2 on 2025-02-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0009_rename_instruccio_prova_script'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='connexio_ssh',
            field=models.BooleanField(default=True, help_text='DEPRECATED, no utilitzar. Veure TIPUS en el seu lloc.'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='script',
            field=models.TextField(help_text='Instruccions a executar. Veure "tipus" per seleccionar el llenguatge. Utilitza %IP per la IP del client.'),
        ),
        migrations.AlterField(
            model_name='prova',
            name='tipus',
            field=models.CharField(choices=[('BASHCLI', 'Script bash al client'), ('BASHSRV', 'Script bash al servidor'), ('SELESRV', 'Script Selenium en JavaScript des del servidor')], default='BASHCLI', max_length=8),
        ),
    ]
