# Generated by Django 4.2 on 2026-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0010_alter_prova_connexio_ssh_alter_prova_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intent',
            name='isard_user_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='intent',
            name='isard_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='intent',
            name='mac',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
