# Generated by Django 4.2 on 2026-06-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0011_intent_isard_user_id_intent_isard_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterficieVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, null=True)),
                ('nom_escriptori', models.CharField(max_length=17, null=True)),
                ('usuari_isard_id', models.CharField(max_length=100, null=True)),
                ('nom_usuari_isard', models.CharField(max_length=100, null=True)),
                ('compte', models.IntegerField(default=1, help_text="Si aquest valor és >1 vol dir que s'ha reptetit una mac en algun moment donat. Es registraran les dades finals, no les originals.")),
                ('dades', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='intent',
            old_name='isard_user_id',
            new_name='nom_usuari_isard',
        ),
        migrations.RenameField(
            model_name='intent',
            old_name='isard_username',
            new_name='usuari_isard_id',
        ),
    ]
