# Generated by Django 4.2 on 2026-06-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0012_interficievm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interficievm',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interficievm',
            name='mac',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
