# Generated by Django 4.2 on 2026-06-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0013_interficievm_timestamp_alter_interficievm_mac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interficievm',
            old_name='timestamp',
            new_name='actualitzat',
        ),
    ]
