# Generated by Django 4.2 on 2026-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0014_rename_timestamp_interficievm_actualitzat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interficievm',
            name='nom_escriptori',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
