# Generated by Django 4.2 on 2026-10-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0015_alter_interficievm_nom_escriptori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='tester.categoria'),
        ),
    ]
